name: Build and Deploy Gatsby Site

on:
  push:
    branches:
      - master
      - ga-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Gatsby CLI
      run: npm install -g gatsby-cli

    - name: Install dependencies
      run: npm ci

    - name: Build Gatsby site
      run: npm run build
      env:
        GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
    
    - name: Copy site to DigitalOcean
      run: |
        TEMP=$(mktemp)
        echo "${{ secrets.SSH_KEY }}" > $TEMP
        scp -o 'StrictHostKeyChecking no' -i $TEMP -r public/ root@137.184.109.231:/data/public
